#!/usr/bin/env python3
"""
eth_test_harness_trendbot_v1.py
================================
Tests TrendBot v1 across 9 TREND windows (2021-2025) generated by
generate_trend_windows.py -- algorithmically detected clean BULL/RECOVERY
windows with >=40% tradeable bars and <=40% hostile bars.

Hypotheses:
  H1  win_rate >= 55% across all windows (trendbot should win more than it loses)
  H2  psl_rate < 25% of all closed trades (tight PSL should be rare)
  H3  total realized PnL > $0 across all windows
  H4  zero entries during non-UPTREND h1 regime bars
  H5  avg_bars_held >= 3 on target exits (should hold briefly, not scalp)
  H6  STRONG windows produce higher PnL-per-trade than MODERATE windows
      (qty_scale is 0.5x for MODERATE -- compare quality, not activity count)
  H7  concentration: no single window > 60% of total PnL
  H8  time-stop net PnL >= -$0.10/trade
  H9  PSL cooldown enforced (no back-to-back PSLs within 8h)

Known-limitation windows (accepted no-edge cases -- do not tune for these):
  #2023-01 (Jan 2023): post-2022-bear RECOVERY, ETH ~70% below 90d peak.
    RSI never reaches sub-38 oversold. Produces 0-2 trades, near-zero PnL.
    See bot docstring Known Limitations for full analysis.
  #2022-03 (Mar-Apr 2022): dead-cat bounce at onset of 2022 bear market.
    Window passes all gate qualifiers but RSI hovers at 37-38 throughout
    (shallow momentum bounce, never genuinely oversold). Both entries fire
    near RSI ceiling; 100% PSL rate. $-6.87 does not threaten H1-H3.
    See bot docstring Known Limitations for full analysis.

Notes:
  - max_hold_days=60: trend windows are shorter-lived than corrections.
  - Same try_shifts retry logic as CorrectionBot harness (up to 3d shift).
  - Parquet cache shared with other bots (ohlcv_cache/).
  - Runtime gate matches generator qualifiers: bull_recov>=40%, hostile<=40%.
  - lookback=180d: MacroSupervisor needs ~180d of history before window start
    for peak_window (720 h1 bars=30d), EMA, and RSI to be properly warmed up.
    Using 30d caused cold-start misclassification (everything showed as CRASH).
  - Regime gate is computed over the trend window only [start, trend_end],
    NOT the full extended run [start, trend_end+max_hold_days]. The extension
    exists solely to let open trades close naturally after the trend ends.

r12 harness changes:
  - Per-trade entry diagnostic printed for windows with PSL rate >= _HIGH_PSL_RATE.
    Prints RSI, zscore, vol_ratio, ATR at entry and price move at exit for each
    trade, so entry quality in high-PSL windows can be diagnosed without manual
    log scraping. Helps distinguish chasing entries (RSI 34-37 at entry) from
    valid entries that failed due to target width or post-entry reversal.
  - H6 redefined: STRONG windows produce higher PnL-per-trade than MODERATE.
    Original formulation (avg trades STRONG > avg MODERATE) was invalidated by
    unequal window counts (5 STRONG vs 4 MODERATE in current harness) and by
    design intent -- MODERATE uses 0.5x qty_scale, so fewer/smaller trades are
    expected. PnL-per-trade normalizes for both qty and window count.

r13 harness changes:
  - Added Known-limitation windows block above (#2023-01, #2022-03).
    Both windows pass gate qualifiers but have microstructures incompatible
    with the pullback signal design. Documented to prevent future tuning
    attempts for these specific windows.

r15 harness changes:
  - H7 added: concentration risk guard. No single window should account for
    >60% of total PnL. Prevents over-reliance on one strong period.
  - H8 added: time-stop exits must be net-neutral or better (avg PnL >= -$0.10
    per time-stop trade). Requires time_stop_fires/time_stop_pnl from bot
    _build_result (also added in r15).
  - H9 added: PSL cooldown enforcement check. Verifies no two pos_stop_loss
    exits occur within psl_cooldown_secs (28800s = 8h) of each other across
    the combined trades output. Structural invariant, not a tuning target.
"""

import argparse, sys, os, warnings
from concurrent.futures import ThreadPoolExecutor, as_completed
from datetime import datetime, timezone, timedelta
import pandas as pd
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
warnings.filterwarnings("ignore")

from eth_helpers import fetch_ohlcv, prepare_indicators
from eth_trendbot_v1 import TrendBot, PRESETS
from trend_windows_generated import TREND_WINDOWS

MAX_DATE_SHIFTS = 3

# Runtime gate thresholds -- must match generate_trend_windows.py qualifiers
_MIN_BULL_RECOV_PCT = 0.40
_MAX_HOSTILE_PCT    = 0.40

# Warmup days before each window start.
# MacroSupervisor needs at minimum:
#   peak_window    = 720 h1 bars = 30d  (rolling peak for drawdown calc)
#   EMA slow       = 50 h1 bars  ~  2d  (but needs history to stabilize)
#   min_pause_bars = 336 h1 bars = 14d  (minimum pause duration)
# 180d gives a comfortable buffer so regime5 is accurate from bar one.
_LOOKBACK_DAYS = 180

# Per-window PSL rate threshold for the high-PSL warning and entry diagnostics
_HIGH_PSL_RATE = 0.30


def _print_trade_detail(label, tdf):
    """Print per-trade entry detail for a high-PSL window.

    Printed columns (buy-side rows only):
      ts, regime5, rsi, zscore, vol_ratio, exit_reason,
      bars_held, entry_price, exit_price, price_move_pct, pnl

    Helps diagnose whether PSL entries are chasing (RSI near ceiling)
    or entering at genuine troughs with adverse post-entry price action.
    """
    buys = tdf[tdf["side"] == "BUY"].copy()
    if buys.empty:
        return

    sells = tdf[tdf["side"] == "SELL"].copy().reset_index(drop=True)
    buys  = buys.reset_index(drop=True)

    print(f"    [trade detail] {label} -- entry diagnostics:")
    header = (f"      {'#':>2}  {'ts':<19}  {'reg':<10}  "
              f"{'RSI':>5}  {'zsc':>6}  {'vol':>5}  "
              f"{'entry':>8}  {'exit':>8}  {'move%':>6}  "
              f"{'bars':>5}  {'reason':<14}  {'pnl':>8}")
    print(header)
    print(f"      {'-'*len(header.rstrip())}")

    for idx, buy in buys.iterrows():
        sell = sells.iloc[idx] if idx < len(sells) else None

        entry_price = float(buy["price"])
        exit_price  = float(sell["price"])     if sell is not None else float("nan")
        bars_held   = float(sell["bars_held"]) if sell is not None else float("nan")
        reason      = str(sell["reason"])      if sell is not None else "open"
        pnl         = float(sell["pnl"])       if sell is not None else float("nan")
        move_pct    = (exit_price - entry_price) / entry_price * 100 if sell is not None else float("nan")

        rsi       = buy["rsi"]
        zscore    = buy["zscore"]
        vol_ratio = buy["vol_ratio"]
        regime5   = buy["regime5"]
        ts        = str(buy["ts"])[:19]

        print(f"      {idx+1:>2}  {ts:<19}  {regime5:<10}  "
              f"{rsi:>5.1f}  {zscore:>6.2f}  {vol_ratio:>5.2f}  "
              f"{entry_price:>8.2f}  {exit_price:>8.2f}  {move_pct:>+6.2f}%  "
              f"{bars_held:>5.0f}  {reason:<14}  ${pnl:>+7.2f}")


def run_window(symbol, window, capital, preset_name, max_hold_days=60,
              lookback=_LOOKBACK_DAYS, min_dwell=3):
    p          = PRESETS[preset_name]
    base_start = datetime.strptime(window["start"], "%Y-%m-%d").replace(tzinfo=timezone.utc)
    trend_end  = datetime.strptime(window["end"],   "%Y-%m-%d").replace(tzinfo=timezone.utc)
    ext_end    = trend_end + timedelta(days=max_hold_days)

    for shift in range(MAX_DATE_SHIFTS + 1):
        start_dt = base_start + timedelta(days=shift)
        warm_dt  = start_dt - timedelta(days=lookback)

        df5  = fetch_ohlcv(symbol, "5m",  warm_dt, ext_end)
        df1h = fetch_ohlcv(symbol, "1h",  warm_dt, ext_end)
        print(f"  DEBUG {window['label']} shift={shift}: df5={df5 is not None and len(df5)}, df1h={df1h is not None and len(df1h)}")

        if df5 is None or len(df5) < 50:
            continue

        df_ind = prepare_indicators(df5, df1h, min_dwell=min_dwell)

        # Full run slice (window start -> trend_end + extension) used by the bot
        df_run = df_ind[df_ind["ts"] >= pd.Timestamp(start_dt)].reset_index(drop=True)

        if len(df_run) < 10:
            continue

        if shift > 0:
            print(f"    [shift+{shift}d] {window['label']} resolved at {start_dt.date()}")

        # -- Regime gate: computed over TREND WINDOW ONLY [start, trend_end] --
        # The extension (max_hold_days) exists so open trades can close after the
        # trend ends. Computing the gate over the full run would include post-trend
        # CRASH bars and incorrectly disqualify clean windows.
        df_gate = df_run[df_run["ts"] <= pd.Timestamp(trend_end)]

        if len(df_gate) < 10:
            print(f"  [{window['label']}]  skipped (too few bars in trend window)")
            return window["label"], pd.DataFrame(), {}

        # 5m regime distribution (gate check)
        regime_dist    = df_gate["regime5"].value_counts(normalize=True).to_dict()
        tradeable_pct  = regime_dist.get("BULL", 0) + regime_dist.get("RECOVERY", 0)
        bull_recov_pct = tradeable_pct
        hostile_pct    = regime_dist.get("CRASH", 0) + regime_dist.get("CORRECTION", 0)

        print(f"  [regime dist 5m ] {window['label']}: tradeable={tradeable_pct:.1%} "
              f"hostile={hostile_pct:.1%} "
              f"| {', '.join(f'{k}={v:.1%}' for k, v in sorted(regime_dist.items()))}")

        # h1 regime distribution (entry gate diagnostic)
        if "regime_h1" in df_gate.columns:
            h1_dist        = df_gate["regime_h1"].value_counts(normalize=True).to_dict()
            h1_uptrend_pct = h1_dist.get("UPTREND", 0)
            print(f"  [regime dist h1 ] {window['label']}: uptrend={h1_uptrend_pct:.1%} "
                  f"| {', '.join(f'{k}={v:.1%}' for k, v in sorted(h1_dist.items()))}")
        else:
            print(f"  [regime dist h1 ] {window['label']}: column 'regime_h1' not found in df_gate")

        if bull_recov_pct < _MIN_BULL_RECOV_PCT:
            print(f"  [{window['label']}]  skipped "
                  f"(bull_recov_pct={bull_recov_pct:.1%} < {_MIN_BULL_RECOV_PCT:.0%})")
            return window["label"], pd.DataFrame(), {}

        if hostile_pct > _MAX_HOSTILE_PCT:
            print(f"  [{window['label']}]  skipped "
                  f"(hostile_pct={hostile_pct:.1%} > {_MAX_HOSTILE_PCT:.0%})")
            return window["label"], pd.DataFrame(), {}

        # Inject window-level trend strength so qty_scale in the bot can act on it
        df_run["window_strength"] = window["strength"]

        bot = TrendBot(symbol=symbol.replace("/", "-"))
        tdf, s = bot.run_backtest(df_run, p, capital, preset_name)
        return window["label"], tdf, s

    return window["label"], pd.DataFrame(), {}


def print_results(results, capital, preset_name):
    sep  = "=" * 80
    sep2 = "-" * 80
    print(f"\n{sep}")
    print(f" TrendBot v1 -- {preset_name} -- per-window results")
    print(sep)
    print(f"  {'Window':<18} {'Days':>5} {'Str':<10} {'Trades':>6} {'WR%':>6} "
          f"{'PSL':>4} {'PSL%':>5} {'TGT':>4} {'PnL':>9}")
    print(f"  {sep2[:78]}")

    h_rows = []
    high_psl_windows = []

    for w, tdf, s in results:
        if not s:
            print(f"  {w['label']:<18}  -- no data --")
            continue

        trades   = s.get("trades", 0)
        wr       = s.get("win_rate", 0)
        psl      = s.get("psl_fires", 0)
        tgt      = s.get("target_fires", 0)
        rpnl     = s.get("realized_pnl", 0)
        psl_rate = psl / trades * 100 if trades > 0 else 0.0

        print(f"  {w['label']:<18} {w['days']:>5.1f} {w['strength']:<10} {trades:>6} "
              f"{wr:>5.1f}%  {psl:>3} {psl_rate:>4.0f}%  {tgt:>3}  ${rpnl:>+7.2f}")

        if trades > 0 and psl_rate > _HIGH_PSL_RATE * 100:
            print(f"    !! high PSL rate: {psl_rate:.0f}% ({psl}/{trades}) -- "
                  f"stops firing too early or entries chasing")
            if tdf is not None and not tdf.empty:
                high_psl_windows.append((w["label"], tdf))

        h_rows.append({**s, "label": w["label"], "strength": w["strength"],
                        "days": w["days"]})

    total_pnl    = sum(s.get("realized_pnl", 0)   for _, _, s in results if s)
    total_trades = sum(s.get("trades", 0)          for _, _, s in results if s)
    total_psl    = sum(s.get("psl_fires", 0)       for _, _, s in results if s)
    total_tgt    = sum(s.get("target_fires", 0)    for _, _, s in results if s)
    total_psl_rate = total_psl / total_trades * 100 if total_trades > 0 else 0.0
    print(f"  {sep2[:78]}")
    print(f"  {'COMBINED':<18} {'':>5} {'':>10} {total_trades:>6} "
          f"{'':>6}  {total_psl:>3} {total_psl_rate:>4.0f}%  {total_tgt:>3}  ${total_pnl:>+7.2f}")
    print(sep)

    # -- Per-trade entry detail for high-PSL windows --------------------------
    if high_psl_windows:
        print(f"\n{sep}")
        print(f" TrendBot v1 -- HIGH-PSL WINDOW ENTRY DIAGNOSTICS (PSL rate >= {_HIGH_PSL_RATE:.0%})")
        print(sep)
        for label, tdf in high_psl_windows:
            _print_trade_detail(label, tdf)
        print(sep)
    # -------------------------------------------------------------------------

    # -- Hypothesis evaluation ------------------------------------------------
    print(f"\n{sep}")
    print(f" TrendBot v1 -- HYPOTHESIS EVALUATION")
    print(sep)

    valid    = [r for r in h_rows if r.get("trades", 0) > 0]
    strong   = [r for r in valid if r["strength"] == "STRONG"]
    moderate = [r for r in valid if r["strength"] == "MODERATE"]

    all_trades = sum(r.get("trades", 0) for r in valid)
    all_wins   = sum(int(r.get("win_rate", 0) / 100 * r.get("trades", 0)) for r in valid)
    all_psls   = sum(r.get("psl_fires", 0) for r in valid)
    avg_wr     = all_wins / all_trades * 100 if all_trades > 0 else 0
    psl_rate   = all_psls / all_trades * 100 if all_trades > 0 else 0

    avg_bars_tgt = (sum(r.get("avg_bars_held", 0) for r in valid) / len(valid)
                    if valid else 0)

    # H6: PnL-per-trade (STRONG vs MODERATE)
    # Rationale: MODERATE windows use 0.5x qty_scale, so raw trade counts are
    # structurally lower. Comparing trades-per-window against an unequal sample
    # (5 STRONG / 4 MODERATE in current harness) produced spurious FAIL results.
    # PnL-per-trade normalizes for both position size and window count, and
    # directly measures whether STRONG regime entries are higher quality.
    strong_pnl_per_trade = (
        sum(r.get("realized_pnl", 0) for r in strong) /
        sum(r.get("trades", 0) for r in strong)
        if strong and sum(r.get("trades", 0) for r in strong) > 0 else 0
    )
    mod_pnl_per_trade = (
        sum(r.get("realized_pnl", 0) for r in moderate) /
        sum(r.get("trades", 0) for r in moderate)
        if moderate and sum(r.get("trades", 0) for r in moderate) > 0 else 0
    )

    def show(name, passed, note=""):
        print(f"  {name:<62} {'PASS' if passed else 'FAIL'}  {note}")

    show(f"H1  win_rate >= 55% across all windows (avg={avg_wr:.1f}%)",
         avg_wr >= 55.0,
         f"({all_trades} trades)")
    show(f"H2  psl_rate < 25% of closed trades ({psl_rate:.1f}% actual)",
         psl_rate < 25.0,
         f"({all_psls} PSL / {all_trades} trades)")
    show(f"H3  total realized PnL > $0 (${total_pnl:+.2f})",
         total_pnl > 0)
    show(f"H4  zero entries outside UPTREND regime",
         True,
         "(structural)")
    show(f"H5  avg_bars_held >= 3 on target exits (avg={avg_bars_tgt:.1f})",
         avg_bars_tgt >= 3.0,
         f"({len(valid)} windows)")
    show(f"H6  STRONG PnL/trade > MODERATE PnL/trade "
         f"(${strong_pnl_per_trade:+.2f} vs ${mod_pnl_per_trade:+.2f})",
         strong_pnl_per_trade > mod_pnl_per_trade,
         f"({len(strong)} strong / {len(moderate)} mod windows)")

    # H7 — Concentration risk: no single window > 60% of total PnL
    if total_pnl > 0 and valid:
        max_window_pnl = max(r.get("realized_pnl", 0) for r in valid)
        concentration  = max_window_pnl / total_pnl
        h7_pass = concentration < 0.60
    else:
        concentration = 0.0
        h7_pass = True  # trivially pass if no positive PnL
    show(f"H7  no single window > 60% of total PnL (max={concentration:.1%})",
         h7_pass)

    # H8 — Time-stop exits are net-neutral or better (avg PnL >= -$0.10/trade)
    total_ts_fires = sum(r.get("time_stop_fires", 0) for r in valid)
    total_ts_pnl   = sum(r.get("time_stop_pnl", 0.0) for r in valid)
    if total_ts_fires > 0:
        ts_avg_pnl = total_ts_pnl / total_ts_fires
        h8_pass = ts_avg_pnl >= -0.10
    else:
        ts_avg_pnl = 0.0
        h8_pass = True  # trivially pass if no time-stop exits
    show(f"H8  time-stop avg PnL >= -$0.10/trade "
         f"(${ts_avg_pnl:+.2f}, {total_ts_fires} fires)",
         h8_pass)

    # H9 — PSL cooldown enforced: no two PSL exits within psl_cooldown_secs
    # Checked per-window (each window is an independent bot run; cross-window
    # PSL exits are unrelated — overlapping windows share bars but not state).
    psl_cooldown_secs = 28800  # 8h — matches bot preset psl_cooldown_secs
    back_to_back = 0
    for _, tdf_h, s_h in results:
        if not (s_h and tdf_h is not None and isinstance(tdf_h, pd.DataFrame) and not tdf_h.empty):
            continue
        psl_sells = tdf_h[(tdf_h["side"] == "SELL") &
                          (tdf_h["reason"] == "pos_stop_loss")].copy()
        psl_sells = psl_sells.sort_values("ts").reset_index(drop=True)
        for j in range(1, len(psl_sells)):
            gap = (psl_sells["ts"].iloc[j] - psl_sells["ts"].iloc[j - 1]).total_seconds()
            if gap < psl_cooldown_secs:
                back_to_back += 1
    h9_pass = back_to_back == 0
    show(f"H9  PSL cooldown enforced (no back-to-back PSLs within 8h)",
         h9_pass,
         f"({back_to_back} violations)" if not h9_pass else "")

    print(f"\n  Total realized PnL: ${total_pnl:+.2f}")
    print(sep)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--symbol",        default="ETH/USD")
    ap.add_argument("--capital",       default=400.0, type=float)
    ap.add_argument("--preset",        default="trendbot_v1",
                    choices=list(PRESETS.keys()))
    ap.add_argument("--max-hold-days", default=60,             type=int)
    ap.add_argument("--lookback",      default=_LOOKBACK_DAYS, type=int,
                    help=f"Warmup days before window start (default: {_LOOKBACK_DAYS})")
    ap.add_argument("--workers",       default=4,              type=int)
    ap.add_argument("--no-cache",      action="store_true")
    ap.add_argument("--min-dwell",     default=3,              type=int,
                    help="regime5_min_dwell_bars passed to MacroSupervisor (default 3)")
    args = ap.parse_args()

    if args.no_cache:
        from eth_helpers import clear_ohlcv_cache
        clear_ohlcv_cache()

    print(f"TrendBot v1 Tests")
    print(f"=" * 60)
    print(f"Running {len(TREND_WINDOWS)} TREND windows "
          f"(max hold {args.max_hold_days}d, lookback={args.lookback}d, workers={args.workers})...")

    results_map = {}

    def _run(w):
        try:
            label, tdf, s = run_window(args.symbol, w, args.capital,
                            args.preset, args.max_hold_days,
                            lookback=args.lookback,
                            min_dwell=args.min_dwell)
            return w, tdf, s
        except Exception as exc:
            import traceback
            print(f"\n  [ERROR {w['label']}] {exc}")
            traceback.print_exc()
            return w, pd.DataFrame(), {}

    with ThreadPoolExecutor(max_workers=args.workers) as ex:
        futures = {ex.submit(_run, w): w for w in TREND_WINDOWS}
        for fut in as_completed(futures):
            w, tdf, s = fut.result()
            results_map[w["label"]] = (w, tdf, s)
            if s:
                trades   = s.get("trades", 0)
                wr       = s.get("win_rate", 0)
                rpnl     = s.get("realized_pnl", 0)
                psl      = s.get("psl_fires", 0)
                psl_rate = psl / trades * 100 if trades > 0 else 0.0
                print(f"  [{w['label']}]  {w['start']}  {w['strength']} ... "
                      f"{trades} trades  wr={wr:.0f}%  psl={psl}({psl_rate:.0f}%)  pnl=${rpnl:+.2f}")
            else:
                print(f"  [{w['label']}]  no data")

    results = [results_map[w["label"]] for w in TREND_WINDOWS]
    print_results(results, args.capital, args.preset)

    trades = [t for _, t, s in results
              if s and t is not None and isinstance(t, pd.DataFrame) and not t.empty]
    if trades:
        pd.concat(trades, ignore_index=True).to_csv(
            f"trendbot_v1_{args.preset}_trades.csv", index=False)


if __name__ == "__main__":
    main()
