#!/usr/bin/env python3
"""
trend_windows_generated.py -- Auto-generated by generate_trend_windows.py

DO NOT EDIT BY HAND. Re-run generate_trend_windows.py to regenerate.

Qualification criteria applied at generation time:
  - min_bull_recov_pct >= 40% of h1 bars are BULL/RECOVERY
  - max_hostile_pct    <= 40% of h1 bars are CRASH/CORRECTION
  - min_days           >= 7 calendar days
  - min_gain_pct       >= 8% price gain over window
  - Windows with passes=False are included as comments for audit trail.
"""

TREND_WINDOWS = [
    # -- 2021 --------------------------------------------------------------------
    {
        "label":    "#2021-03",
        "start":    "2021-03-26",
        "end":      "2021-04-07",
        "days":     11.4,
        "gain_pct": +26.6,
        "strength": "STRONG",
        # tradeable=99% hostile=0% | bull=38% recov=61% crash=0% corr=0%
    },
    {
        "label":    "#2021-04",
        "start":    "2021-04-21",
        "end":      "2021-05-04",
        "days":     13.2,
        "gain_pct": +37.8,
        "strength": "STRONG",
        # tradeable=99% hostile=0% | bull=46% recov=53% crash=0% corr=0%
    },
    # -- 2022 --------------------------------------------------------------------
    {
        "label":    "#2022-03",
        "start":    "2022-03-15",
        "end":      "2022-03-29",
        "days":     14.1,
        "gain_pct": +31.8,
        "strength": "STRONG",
        # tradeable=100% hostile=0% | bull=50% recov=49% crash=0% corr=0%
    },
    {
        "label":    "#2022-08",
        "start":    "2022-08-05",
        "end":      "2022-08-16",
        "days":     11.0,
        "gain_pct": +14.1,
        "strength": "MODERATE",
        # tradeable=100% hostile=0% | bull=36% recov=64% crash=0% corr=0%
    },
    # -- 2023 --------------------------------------------------------------------
    {
        "label":    "#2023-01",
        "start":    "2023-01-02",
        "end":      "2023-01-16",
        "days":     14.0,
        "gain_pct": +29.2,
        "strength": "STRONG",
        # tradeable=100% hostile=0% | bull=50% recov=50% crash=0% corr=0%
    },
    {
        "label":    "#2023-10",
        "start":    "2023-10-16",
        "end":      "2023-10-24",
        "days":     8.4,
        "gain_pct": +12.9,
        "strength": "MODERATE",
        # tradeable=98% hostile=0% | bull=98% recov=0% crash=0% corr=0%
    },
    # -- 2024 --------------------------------------------------------------------
    {
        "label":    "#2024-02",
        "start":    "2024-02-12",
        "end":      "2024-02-23",
        "days":     11.0,
        "gain_pct": +16.3,
        "strength": "MODERATE",
        # tradeable=100% hostile=0% | bull=36% recov=64% crash=0% corr=0%
    },
    {
        "label":    "#2024-11",
        "start":    "2024-11-18",
        "end":      "2024-12-02",
        "days":     13.4,
        "gain_pct": +18.1,
        "strength": "MODERATE",
        # tradeable=99% hostile=0% | bull=47% recov=52% crash=0% corr=0%
    },
    # -- 2025 --------------------------------------------------------------------
    {
        "label":    "#2025-07",
        "start":    "2025-07-11",
        "end":      "2025-07-22",
        "days":     11.0,
        "gain_pct": +29.3,
        "strength": "STRONG",
        # tradeable=100% hostile=0% | bull=36% recov=63% crash=0% corr=0%
    },
]